// src/lib/blockchain/waves/deployed.config.ts
// AUTO-GENERATED by KrossBuild dApp pipeline — chain-specific deployment config.
// Do not hardcode addresses elsewhere; read from here.
export const DEPLOYED_CONFIG = {
  "chain": "waves",
  "chainId": "W",
  "nodeUrl": "https://nodes.wavesnodes.com",
  "explorerUrl": "https://wavesexplorer.com",
  "addressPrefix": "3P",
  "nativeCoin": {
    "name": "Waves",
    "symbol": "WAVES",
    "decimals": 8
  },
  "language": "RIDE",
  "contracts": []
} as const;
export default DEPLOYED_CONFIG;
