// src/lib/blockchain/kross/deployed.config.ts
// AUTO-GENERATED by KrossBuild dApp pipeline — chain-specific deployment config.
// Do not hardcode addresses elsewhere; read from here.
export const DEPLOYED_CONFIG = {
  "chain": "kross",
  "chainId": "N",
  "nodeUrl": "https://nodes.krossexplorer.com",
  "explorerUrl": "https://krossexplorer.com",
  "addressPrefix": "3K",
  "nativeCoin": {
    "name": "Kross",
    "symbol": "KSS",
    "decimals": 8
  },
  "language": "RIDE",
  "contracts": []
} as const;
export default DEPLOYED_CONFIG;
