// src/lib/blockchain/kross/deployed.config.ts
// AUTO-GENERATED by KrossBuild dApp pipeline — chain-specific deployment config.
// Do not hardcode addresses elsewhere; read from here.
// Marketplace economics + governance (single source of truth for the client).
// Addresses are Kross base58 with the 3K prefix.
export const MARKETPLACE_PARAMS = {
  // ===== REPLACE WITH REAL KROSS (3K...) ADDRESSES BEFORE DEPLOY =====
  // Must exactly match OWNER_ADDRESS_PLACEHOLDER / FEE_WALLET_ADDRESS_PLACEHOLDER
  // in contracts/kross-marketplace.ride.
  // Contract admin (deployer). Becomes owner via init().
  ownerAddress: "3KOwnerAddressReplaceMeXXXXXXXXXXXXXX",
  // Wallet that receives the platform fee.
  feeWalletAddress: "3KFeeWalletReplaceMeXXXXXXXXXXXXXXXXX",
  // ==================================================================
  // Platform fee (configurable on-chain by owner).
  feeBasisPoints: 250,        // 2.5%
  feePercent: 2.5,
  // Creator royalty paid to the NFT issuer (resolved on-chain via
  // assetInfo().issuer) on EVERY sale — incl. all secondary sales, forever.
  royaltyBasisPoints: 250,    // 2.5%
  royaltyPercent: 2.5,
} as const;

// dApp address + entrypoint names consumed by the marketplace sale endpoint.
// `dAppAddress` falls back to the build-time env var when present.
const _ENV_DAPP =
  (typeof import.meta !== 'undefined' &&
    (import.meta as unknown as { env?: Record<string, string> }).env
      ?.VITE_KROSS_MARKETPLACE_DAPP) ||
  '';

export const MARKETPLACE_CONFIG = {
  // Deployed marketplace dApp (the contract account). Replace the placeholder
  // or set VITE_KROSS_MARKETPLACE_DAPP at build time.
  dAppAddress: _ENV_DAPP || "<MARKETPLACE_DAPP_ADDRESS_BASE58>",
  functions: {
    list: 'listNFT',
    update: 'updateListing',
    updatePrice: 'updatePrice',
    cancel: 'cancelListing',
    buy: 'buyNFT',
  },
} as const;

export const DEPLOYED_CONFIG = {
  "chain": "kross",
  "chainId": "N",
  "nodeUrl": "https://nodes.krossexplorer.com",
  "explorerUrl": "https://krossexplorer.com",
  "addressPrefix": "3K",
  "nativeCoin": {
    "name": "Kross",
    "symbol": "KSS",
    "decimals": 8
  },
  "language": "RIDE",
  "contracts": []
} as const;
export default DEPLOYED_CONFIG;
