// AUTO-GENERATED by KrossBuild — points this app at its managed Krossable Cloud backend.
// Do not edit by hand; re-provision the backend from Settings to regenerate.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://lzspyqrfizzketrtvpcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6c3B5cXJmaXp6a2V0cnR2cGNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE2MzczNDYsImV4cCI6MjA5NzIxMzM0Nn0.gLvPnHs4IK6eRqW1gQikb4254aEV-D7m7jUhyj1eF6Y";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  },
});
